export const helpCategories = [
  {
    id: "quick-start",
    title: "快速开始",
    description: "完成首次设置，选择适合自己的口语练习方式。",
    icon: "rocket",
  },
  {
    id: "account-login",
    title: "账号与登录",
    description: "了解注册、登录、个人资料和密码安全。",
    icon: "account",
  },
  {
    id: "ai-training",
    title: "AI 对话与训练",
    description: "使用自由对话和情景口语完成一次完整练习。",
    icon: "conversation",
  },
  {
    id: "audio",
    title: "麦克风和音频",
    description: "排查麦克风权限、播放声音和实时连接问题。",
    icon: "microphone",
  },
  {
    id: "learning-records",
    title: "学习记录",
    description: "查看学习资产、评分、打卡和练习统计。",
    icon: "records",
  },
  {
    id: "membership",
    title: "会员与额度",
    description: "了解当前会员页面、额度提示和功能开放状态。",
    icon: "membership",
  },
  {
    id: "privacy-security",
    title: "隐私与安全",
    description: "保护账号信息，安全使用麦克风并提交问题反馈。",
    icon: "security",
  },
  {
    id: "feedback",
    title: "问题反馈",
    description: "整理问题信息，帮助我们更快定位使用异常。",
    icon: "feedback",
  },
];

export const helpArticles = [
  {
    id: "complete-first-time-setup",
    categoryId: "quick-start",
    title: "如何完成首次设置并开始练习？",
    summary: "设置英语水平和 AI 老师后，即可进入自由对话或情景训练。",
    keywords: ["首次使用", "英语水平", "AI 老师", "开始练习"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "注册或登录", body: "使用邮箱和密码进入 UniSpeaking。首次注册后，系统会引导你完成基础偏好设置。" },
      { title: "选择英语水平", body: "选择最接近当前口语状态的等级。这个设置用于调整 AI 的表达难度，之后可以在助手设置中修改。" },
      { title: "选择 AI 老师", body: "试听并选择一位 AI 老师。完成后会进入主应用，你可以从自由对话或场景广场开始练习。" },
    ],
  },
  {
    id: "choose-practice-mode",
    categoryId: "quick-start",
    title: "自由对话和情景训练有什么区别？",
    summary: "自由对话适合即时开口，情景训练适合围绕具体任务循序练习。",
    keywords: ["自由对话", "场景广场", "情景训练", "练习模式"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "需要马上开口时", body: "选择自由对话。你可以直接与 AI 老师进行实时语音交流，并按需要查看字幕或翻译。" },
      { title: "需要明确主题时", body: "选择场景广场。输入想练习的情景后，系统会生成相关单词、词组、句子和对话任务。" },
      { title: "根据目标组合使用", body: "可以先在情景训练中学习表达，再进入模拟对话；日常热身或开放话题则更适合自由对话。" },
    ],
  },
  {
    id: "adjust-assistant-settings",
    categoryId: "quick-start",
    title: "如何更换英语水平、AI 老师和语速？",
    summary: "在个人中心的助手设置中调整对话体验。",
    keywords: ["助手设置", "语速", "老师", "难度", "英语水平"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "进入个人中心", body: "点击全局左侧栏底部的头像，然后选择“助手设置”。" },
      { title: "调整偏好", body: "选择新的对话语速、英语水平或 AI 老师。设置会在页面中自动保存。" },
      { title: "开始新对话", body: "新的偏好会用于之后开始的对话。正在进行中的实时会话不会被强制中断。" },
    ],
  },
  {
    id: "register-and-login",
    categoryId: "account-login",
    title: "如何注册和登录 UniSpeaking？",
    summary: "使用有效邮箱和密码创建账号，之后可从登录页再次进入。",
    keywords: ["注册", "登录", "邮箱", "密码", "账号"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "创建账号", body: "在注册页面填写邮箱和密码，并按页面提示提交。密码长度需要满足当前表单要求。" },
      { title: "完成首次设置", body: "注册成功后选择英语水平和 AI 老师，完成后进入主应用。" },
      { title: "再次登录", body: "之后使用同一邮箱和密码登录。如果登录状态失效，系统会自动返回登录页。" },
    ],
  },
  {
    id: "change-account-password",
    categoryId: "account-login",
    title: "如何修改账号密码？",
    summary: "在助手设置中验证当前密码并设置新密码。",
    keywords: ["修改密码", "当前密码", "新密码", "账户安全"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "打开账户与隐私", body: "进入个人中心的“助手设置”，在“账户与隐私”区域选择“修改密码”。" },
      { title: "填写密码", body: "输入当前密码和新密码。新密码不能与当前密码相同，长度需要为 6 至 72 位。" },
      { title: "重新登录", body: "修改成功后，当前设备和其他设备上的旧登录状态都会失效，请使用新密码重新登录。" },
    ],
  },
  {
    id: "why-login-expired",
    categoryId: "account-login",
    title: "为什么系统要求我重新登录？",
    summary: "登录凭证失效、密码变更或账号状态变化时，系统会要求重新认证。",
    keywords: ["重新登录", "登录失效", "JWT", "认证", "退出"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "确认是否修改过密码", body: "修改密码会立即使全部旧登录状态失效，这是保护账号安全的正常行为。" },
      { title: "返回登录页", body: "清除已失效的登录状态后，使用当前邮箱和最新密码重新登录。" },
      { title: "仍无法登录时", body: "确认邮箱拼写和密码输入无误，再通过问题反馈页整理发生时间、页面提示和浏览器信息。不要提交密码原文。" },
    ],
  },
  {
    id: "update-profile-details",
    categoryId: "account-login",
    title: "如何修改昵称和头像？",
    summary: "通过个人概览顶部的编辑按钮更新展示昵称和个人头像。",
    keywords: ["个人资料", "昵称", "用户名", "头像", "JPEG", "PNG"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "进入个人概览", body: "点击左侧栏底部头像进入个人中心，在资料头像右上角选择编辑按钮。" },
      { title: "修改资料", body: "昵称去除首尾空格后不能为空；头像支持 JPEG 或 PNG，文件不能超过 2 MiB。" },
      { title: "保存并检查", body: "保存成功后，个人中心和全局侧边栏会显示新的昵称或头像。登录邮箱不会随昵称一起修改。" },
    ],
  },
  {
    id: "start-free-conversation",
    categoryId: "ai-training",
    title: "如何开始一次 AI 自由对话？",
    summary: "进入自由对话，确认麦克风可用后开始实时语音交流。",
    keywords: ["AI 对话", "自由对话", "实时语音", "开始", "老师"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "进入自由对话", body: "从全局左侧主导航选择“自由对话”，确认当前 AI 老师、语速和英语水平。" },
      { title: "允许麦克风", body: "首次使用时，浏览器会请求麦克风权限。允许后再开始连接。" },
      { title: "结束会话", body: "完成练习后使用页面中的结束按钮正常结束。正常结束的有效会话会用于学习时长统计。" },
    ],
  },
  {
    id: "create-custom-scene",
    categoryId: "ai-training",
    title: "如何创建自己的情景口语训练？",
    summary: "描述想练习的真实情景，由系统生成对应学习内容。",
    keywords: ["情景训练", "自定义场景", "场景广场", "生成", "提示"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "打开场景广场", body: "从全局主导航进入“场景广场”，找到自定义场景输入区域。" },
      { title: "描述练习目标", body: "输入具体情景，例如办理入住、参加会议或咨询健身房。清楚说明人物、地点和目标会更容易生成合适内容。" },
      { title: "开始训练", body: "生成完成后，按页面引导学习单词、词组和句子，最后进入模拟对话。" },
    ],
  },
  {
    id: "learn-read-speak-flow",
    categoryId: "ai-training",
    title: "“学、读、说”三个阶段分别做什么？",
    summary: "先理解表达，再练习朗读，最后在完整情景中开口。",
    keywords: ["学读说", "单词", "词组", "句子", "朗读", "模拟对话"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "学", body: "学习场景相关的单词和词组，查看英文、中文含义并播放示范发音。" },
      { title: "读", body: "朗读场景句子并查看发音评分和需要关注的部分。" },
      { title: "说", body: "进入完整模拟对话，将刚学到的表达用于真实交流。正常完成后可以查看本次表现。" },
    ],
  },
  {
    id: "use-subtitles-and-translation",
    categoryId: "ai-training",
    title: "如何使用字幕和翻译？",
    summary: "在实时对话中按需要显示完整字幕并翻译对话内容。",
    keywords: ["字幕", "翻译", "中文", "实时对话", "看不懂"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "打开字幕", body: "在对话控制区选择字幕按钮，查看已经完成的对话文本。" },
      { title: "查看翻译", body: "对需要理解的内容使用翻译操作。翻译可能需要短暂等待网络响应。" },
      { title: "继续以开口为主", body: "字幕和翻译适合辅助理解。建议先听完并尝试回答，再在需要时查看文字。" },
    ],
  },
  {
    id: "finish-training-correctly",
    categoryId: "ai-training",
    title: "怎样正确结束一次训练？",
    summary: "使用页面中的结束操作，让系统完成会话收尾和结果保存。",
    keywords: ["结束训练", "报告", "保存", "会话", "退出"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "使用结束按钮", body: "不要直接关闭浏览器标签页，优先使用当前训练页面提供的结束或退出操作。" },
      { title: "等待收尾完成", body: "部分训练需要短暂等待评分或结果生成，期间保持页面和网络连接。" },
      { title: "查看结果", body: "正常完成后，可在结果页或学习资产中查看当前版本已经支持的对话记录和评分。" },
    ],
  },
  {
    id: "grant-microphone-permission",
    categoryId: "audio",
    title: "如何允许浏览器使用麦克风？",
    summary: "在浏览器权限提示中允许麦克风，并选择正确的输入设备。",
    keywords: ["麦克风权限", "浏览器权限", "录音", "允许", "输入设备"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "触发权限请求", body: "进入需要录音的自由对话或训练页面，并选择开始。浏览器会显示麦克风权限提示。" },
      { title: "选择允许", body: "允许当前站点使用麦克风。如果有多个输入设备，请选择正在使用的耳机或麦克风。" },
      { title: "曾经拒绝过时", body: "打开浏览器地址栏附近的站点权限，将麦克风改为允许，然后刷新页面重试。" },
    ],
  },
  {
    id: "microphone-not-detected",
    categoryId: "audio",
    title: "页面检测不到麦克风怎么办？",
    summary: "检查设备连接、系统输入设置和浏览器站点权限。",
    keywords: ["检测不到", "麦克风不可用", "设备", "系统设置", "录音失败"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "检查设备", body: "确认麦克风或耳机已经连接，并且没有被硬件静音。" },
      { title: "检查系统设置", body: "在系统声音设置中确认正确的输入设备有音量变化，同时允许浏览器访问麦克风。" },
      { title: "重新打开页面", body: "关闭占用麦克风的其他应用，刷新 UniSpeaking 后再次允许权限。" },
    ],
  },
  {
    id: "cannot-hear-ai-audio",
    categoryId: "audio",
    title: "听不到 AI 老师的声音怎么办？",
    summary: "检查输出设备、页面播放状态和系统音量。",
    keywords: ["没有声音", "听不到", "扬声器", "耳机", "播放失败"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "检查输出设备", body: "确认系统声音正在输出到当前扬声器或耳机，并提高设备音量。" },
      { title: "检查页面状态", body: "确认没有启用静音，必要时点击页面中的播放按钮重新播放示范音频。" },
      { title: "排除浏览器限制", body: "先与页面进行一次点击交互，再重新播放；如果仍然失败，刷新页面并重新进入训练。" },
    ],
  },
  {
    id: "realtime-connection-interrupted",
    categoryId: "audio",
    title: "实时对话连接中断后怎么办？",
    summary: "结束异常会话，检查网络和权限后重新开始。",
    keywords: ["连接中断", "网络异常", "实时对话", "重连", "WebRTC"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "确认会话已停止", body: "连接异常后，先确认页面已经停止录音和播放，不要重复点击开始按钮。" },
      { title: "检查网络与权限", body: "确认网络稳定、麦克风权限仍然有效，并关闭可能占用麦克风的其他应用。" },
      { title: "重新开始", body: "返回训练入口重新创建会话。原异常会话通常不能从中断位置继续。" },
    ],
  },
  {
    id: "what-learning-assets-save",
    categoryId: "learning-records",
    title: "学习资产会保存哪些内容？",
    summary: "集中查看已完成场景中的语言材料、对话记录和可用评分。",
    keywords: ["学习资产", "保存内容", "训练记录", "单词", "对话"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "完成场景训练", body: "自定义场景中的单词、词组、句子和已完成会话会形成对应的学习记录。" },
      { title: "打开学习资产", body: "从全局主导航进入“学习资产”，在左侧训练记录中选择一个场景。" },
      { title: "查看详情", body: "可以继续查看语言材料、最近对话以及当前版本已经生成的评分和建议。" },
    ],
  },
  {
    id: "view-conversation-feedback",
    categoryId: "learning-records",
    title: "如何查看对话记录和评分？",
    summary: "从学习资产打开最近完成的场景对话详情。",
    keywords: ["对话记录", "评分", "反馈", "五维报告", "历史"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "选择训练记录", body: "进入学习资产后，从记录列表选择需要复盘的场景。" },
      { title: "打开详情", body: "选择“打开当前学习资产”，查看最近一次完整对话和每轮可用反馈。" },
      { title: "理解结果", body: "评分只反映当前练习表现。过短、异常或尚未完成分析的会话可能不会显示完整结果。" },
    ],
  },
  {
    id: "practice-from-assets",
    categoryId: "learning-records",
    title: "如何从学习资产再次练习？",
    summary: "复用已有场景直接练口语，或从头重新学习内容。",
    keywords: ["复练", "重新练习", "学习资产", "快速练习", "重学"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "打开场景记录", body: "在学习资产中选择一个已经保存的场景。" },
      { title: "选择练习方式", body: "快速复练会直接进入口语阶段；重新学习会从场景语言材料开始。" },
      { title: "完成新会话", body: "正常结束复练后，最新会话结果会用于后续复盘，原有场景内容仍可继续使用。" },
    ],
  },
  {
    id: "understand-checkin-statistics",
    categoryId: "learning-records",
    title: "自动打卡和学习统计是怎样计算的？",
    summary: "打卡来自已生成的训练报告，学习时长来自正常完成的有效会话。",
    keywords: ["自动打卡", "学习时长", "连续天数", "统计", "日历"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "自动打卡", body: "当天存在一份已经持久化的完整训练报告时，学习日历会自动记录当天打卡，无需手动点击。" },
      { title: "学习时长", body: "正常结束且整场达到 30 秒的会话才会计入学习时长，跨越自然日时会按实际时间拆分。" },
      { title: "刷新个人概览", body: "完成训练并等待结果保存后返回个人概览，即可查看更新后的日历、连续天数和七日节奏。" },
    ],
  },
  {
    id: "open-membership-page",
    categoryId: "membership",
    title: "在哪里查看会员与额度页面？",
    summary: "从个人中心进入会员权益，查看当前版本展示的方案和额度信息。",
    keywords: ["会员", "额度", "订阅", "会员权益", "方案"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "进入个人中心", body: "点击全局左侧栏底部的头像。" },
      { title: "选择会员权益", body: "在个人中心左侧导航中选择“会员权益”，查看当前页面提供的方案说明。" },
      { title: "注意当前状态", body: "现阶段会员页面主要用于产品功能展示，正式订阅、计费和权益规则尚未开放。" },
    ],
  },
  {
    id: "membership-payment-status",
    categoryId: "membership",
    title: "当前会员升级会产生真实扣费吗？",
    summary: "不会。当前版本的升级和支付流程是界面演示。",
    keywords: ["支付", "扣费", "升级会员", "模拟支付", "价格"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "识别演示提示", body: "会员升级弹窗会标明当前为支付演示，不会连接真实支付渠道。" },
      { title: "不会产生订单", body: "点击当前演示按钮不会创建真实订单，也不会从银行卡或第三方支付账户扣款。" },
      { title: "等待正式通知", body: "正式订阅上线后，计费周期、价格、退款和权益规则会在产品内提供明确说明。" },
    ],
  },
  {
    id: "understand-quota-reminders",
    categoryId: "membership",
    title: "页面中的额度提示代表什么？",
    summary: "当前额度和特训限制用于展示预期体验，不构成正式计费承诺。",
    keywords: ["额度不足", "剩余次数", "特训版", "限制", "提醒"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "查看提示位置", body: "部分训练入口和会员页面会展示剩余次数、分钟数或升级提示。" },
      { title: "理解当前版本", body: "这些内容目前用于说明未来可能的会员体验，尚不是正式、可结算的账户额度。" },
      { title: "不要据此付款", body: "在正式支付功能上线前，不需要为页面展示的额度信息进行任何线下付款或转账。" },
    ],
  },
  {
    id: "protect-account-security",
    categoryId: "privacy-security",
    title: "如何保护我的 UniSpeaking 账号？",
    summary: "使用独立密码，妥善保管登录状态，并在异常时及时修改密码。",
    keywords: ["账号安全", "密码", "登录状态", "共享设备", "退出登录"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "使用独立密码", body: "不要使用与其他重要账号完全相同的密码，也不要将密码发送给任何人。" },
      { title: "离开共享设备时退出", body: "在公共或共享设备上练习后，从个人中心选择“退出登录”。" },
      { title: "发现异常时修改密码", body: "如果怀疑登录状态泄露，立即修改密码。修改成功会使所有设备上的旧登录状态失效。" },
    ],
  },
  {
    id: "avoid-sensitive-feedback",
    categoryId: "privacy-security",
    title: "提交问题反馈时不应包含哪些信息？",
    summary: "不要提交密码、令牌、密钥、完整身份证明或其他敏感数据。",
    keywords: ["敏感信息", "反馈", "密码", "Token", "隐私"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "不要提交账号凭证", body: "反馈中不得填写密码、JWT、验证码、API Key 或任何临时访问凭证。" },
      { title: "只保留必要内容", body: "截图和问题描述只保留定位问题所需的页面、时间和提示，遮挡邮箱、姓名等无关个人信息。" },
      { title: "描述现象而非秘密数据", body: "说明你执行了什么操作、看到了什么结果以及期望结果，不需要提供后台响应、密钥或完整音频。" },
    ],
  },
  {
    id: "use-microphone-safely",
    categoryId: "privacy-security",
    title: "使用麦克风练习时需要注意什么？",
    summary: "只在开始口语练习时授权麦克风，结束后及时停止会话。",
    keywords: ["麦克风", "隐私", "录音", "权限", "停止"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "按需授权", body: "只有在准备开始实时对话或朗读时才允许站点使用麦克风。" },
      { title: "留意录音状态", body: "页面显示正在录音或会话进行中时，避免讨论与练习无关的敏感内容。" },
      { title: "练习后正常结束", body: "使用页面结束按钮停止会话；如果浏览器仍显示麦克风占用，可关闭页面或在站点权限中撤销访问。" },
    ],
  },
  {
    id: "check-before-feedback",
    categoryId: "feedback",
    title: "反馈问题前应该先做哪些检查？",
    summary: "先确认网络、权限和页面状态，避免重复提交可以自行恢复的问题。",
    keywords: ["问题反馈", "排查", "刷新", "网络", "权限"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "记录当前现象", body: "记下发生问题的页面、操作步骤、时间和页面提示，不要急于连续重复操作。" },
      { title: "完成基础排查", body: "检查网络、麦克风权限和输入输出设备；普通页面显示异常可以尝试刷新一次。" },
      { title: "确认可以复现", body: "如果问题再次出现，整理最短复现步骤，再进入问题反馈页生成反馈摘要。" },
    ],
  },
  {
    id: "prepare-feedback-details",
    categoryId: "feedback",
    title: "一条有效的问题反馈应包含什么？",
    summary: "提供发生位置、复现步骤、实际结果、期望结果和环境信息。",
    keywords: ["反馈内容", "复现步骤", "浏览器", "错误提示", "环境"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "说明发生位置", body: "写明问题发生在自由对话、场景训练、学习资产、个人中心或其他页面。" },
      { title: "描述复现过程", body: "按顺序列出操作步骤，并分别说明实际看到的结果和原本期望的结果。" },
      { title: "补充环境信息", body: "提供操作系统、浏览器名称和大致发生时间。不要在反馈中附带密码、令牌或密钥。" },
    ],
  },
  {
    id: "report-security-concern",
    categoryId: "feedback",
    title: "发现账号或隐私安全问题时怎么办？",
    summary: "先保护账号并停止继续暴露数据，再整理最小必要问题信息。",
    keywords: ["安全问题", "账号异常", "隐私", "泄露", "报告"],
    updatedAt: "2026-08-04",
    steps: [
      { title: "先保护账号", body: "立即修改密码并退出共享设备。如果页面仍在录音或上传，先结束当前操作。" },
      { title: "保留必要证据", body: "记录发生时间、页面路径和不含敏感信息的错误现象。不要转发可用的登录凭证。" },
      { title: "整理反馈摘要", body: "前往问题反馈页选择“隐私与安全”，生成可复制的反馈摘要，等待正式支持渠道确认后再发送。" },
    ],
  },
];

export const popularHelpArticleIds = [
  "complete-first-time-setup",
  "grant-microphone-permission",
  "create-custom-scene",
  "view-conversation-feedback",
  "change-account-password",
  "understand-checkin-statistics",
];
