server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  location ~* \.(?:wav|mp3|m4a|aac|ogg)$ {
    types {
      audio/wav wav;
      audio/mpeg mp3;
      audio/x-m4a m4a;
      audio/aac aac;
      audio/ogg ogg;
    }
    try_files $uri =404;
    add_header Cache-Control "public, max-age=86400" always;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
