--- a/Dockerfile
+++ b/Dockerfile
@@ -6,2 +6,3 @@
 FROM node:${NODE_IMAGE_VERSION} AS deps
+RUN sed -i 's#https://dl-cdn.alpinelinux.org/alpine#https://mirrors.aliyun.com/alpine#g' /etc/apk/repositories
 ARG PNPM_VERSION
@@ -35,2 +36,3 @@
 FROM node:${NODE_IMAGE_VERSION} AS runner
+RUN sed -i 's#https://dl-cdn.alpinelinux.org/alpine#https://mirrors.aliyun.com/alpine#g' /etc/apk/repositories
 WORKDIR /app
