package com.unispeaking.domain.vo.achievement;

public enum AchievementMetricKey {
	COMPLETED_SESSION_COUNT,
	CONTINUOUS_LEARNING_DAYS,
	DISTINCT_COMPLETED_SCENE_COUNT,
	MAX_FINAL_SCORE,
	PRONUNCIATION_EVALUATION_COUNT,
	SAVED_ASSET_COUNT,
	MASTERED_EXPRESSION_COUNT,
	DEMO_AUDIO_PLAY_COUNT,
	MONTHLY_ACTIVE_DAY_COUNT
}
